### ISSUE TITLE
Parameter not detected

### ISSUE THREAD

**Issue by skirge** [PortSwigger/param-miner#36]
Hello
I've an application with following base request:

```
POST /login/ HTTP/1.1
Host: atseashop.com
Connection: close
Content-Length: 46
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Content-Type: application/json
Origin: https://atseashop.com
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://atseashop.com/index.html
Accept-Encoding: gzip, deflate
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7

{"username":"chmiels","password":"Test123&"
}
```

and response

```
HTTP/1.1 200 
Server: nginx/1.17.6
Date: Wed, 16 Sep 2020 18:10:27 GMT
Content-Type: application/json;charset=UTF-8
Connection: close
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 169

{"token":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaG1pZWxzIiwicm9sZXMiOiJjaG1pZWxzIiwiYXVkIjoiY3VzdG9tZXIiLCJpYXQiOjE2MDAyNzk4Mjd9.AZD3hjEwqeVFQMI7TFmBNemuy-YJ6FY5jd_hBTesZA8"}

```

This request contains hidden parameter `admin` which is included in basic wordlist, however it's not detected.

Adding this parameter clearly returns different values:

```
POST /login/ HTTP/1.1
Host: atseashop.com
Connection: close
Content-Length: 64
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Content-Type: application/json
Origin: https://atseashop.com
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://atseashop.com/index.html
Accept-Encoding: gzip, deflate
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7

{"username":"chmiels","password":"Test123&",
"admin" :"true"
}

```
Response

```
HTTP/1.1 200 
Server: nginx/1.17.6
Date: Wed, 16 Sep 2020 19:49:26 GMT
Content-Type: application/json;charset=UTF-8
Connection: close
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 178

{"admin":true,"token":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaG1pZWxzIiwiYXVkIjoiYWRtaW4iLCJyb2xlcyI6ImNobWllbHMiLCJpYXQiOjE2MDAyODU3NjZ9.P2Bik3nzBYgR6-sc-R89_cgIUxqumP3BPGNFuQSdlnw"}

```

and with invalid boolean value return value is different (exception):

```
POST /login/ HTTP/1.1
Host: atseashop.com
Connection: close
Content-Length: 71
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Content-Type: application/json
Origin: https://atseashop.com
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://atseashop.com/index.html
Accept-Encoding: gzip, deflate
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7

{"username":"chmiels","password":"Test123&",
"admin" :"jafkajfjsaf"
}

```
Response
```
HTTP/1.1 400 
Server: nginx/1.17.6
Date: Thu, 17 Sep 2020 04:46:44 GMT
Content-Type: application/json;charset=UTF-8
Connection: close
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 559

{"timestamp":1600318004379,"status":400,"error":"Bad Request","message":"JSON parse error: Cannot deserialize value of type `boolean` from String \"jafkajfjsaf\": only \"true\" or \"false\" recognized; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `boolean` from String \"jafkajfjsaf\": only \"true\" or \"false\" recognized\n at [Source: (PushbackInputStream); line: 2, column: 10] (through reference chain: com.docker.atsea.controller.LoginController$UserLogin[\"admin\"])","path":"/login/"}
```

Request with word `admin` was sent by Param Miner (not attached due to big size).
Part of request:
```
"update":"wrtqvapbefqy5fwd","admin":"wrtqvagc6e8ilywd","purge":"wrtqval311xbx7wd","Control":"wrtqvaqykq3vikwd",
```

Response to request sent by Param Miner with `admin` word is:
```
HTTP/1.1 400 
Server: nginx/1.17.6
Date: Thu, 17 Sep 2020 04:46:45 GMT
Content-Type: application/json;charset=UTF-8
Connection: close
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 572

{"timestamp":1600318005432,"status":400,"error":"Bad Request","message":"JSON parse error: Cannot deserialize value of type `boolean` from String \"wrtqvagc6e8ilywd\": only \"true\" or \"false\" recognized; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `boolean` from String \"wrtqvagc6e8ilywd\": only \"true\" or \"false\" recognized\n at [Source: (PushbackInputStream); line: 1, column: 23823] (through reference chain: com.docker.atsea.controller.LoginController$UserLogin[\"admin\"])","path":"/login/"}
```

Param miner log:
```
Add 'fcbz' cachebuster: false
Add dynamic cachebuster: false
Add header cachebuster: false
include origin in cachebusters: true
learn observed words: false
skip boring words: true
only report unique params: false
response: true
request: true
use basic wordlist: true
use bonus wordlist: false
use custom wordlist: false
custom wordlist path: "/usr/share/dict/words"
bruteforce: false
skip uncacheable: false
dynamic keyload: false
max one per host: false
max one per host+status: false
probe identified params: true
scan identified params: false
enable auto-mine: false
auto-mine headers: false
auto-mine cookies: false
auto-mine params: false
auto-nest params: false
fuzz detect: true
carpet bomb: false
try cache poison: true
twitchy cache poison: false
try method flip: false
try -_ bypass: false
thread pool size: 8
rotation interval: 200
rotation increment: 4
force bucketsize: -1
max bucketsize: 65536
max param length: 32
lowercase headers: true
name in issue: false
canary: "zwrtxqva"
Loaded Param Miner v1.21
    CACHE_ONLY false
Updating active thread pool size to 8
Queued 1 attacks
Setting bucketSize to 2048 due to slow response
Unrecognised type: 6
Initiating json bruteforce on atseashop.com
Identified parameter on atseashop.com: username
```
No more requests are issued (shouldn't be there message about finishing the search?).

Link to application source: https://github.com/skirge/atsea-sample-shop-app.
This application can be run as set of docker containers, using `docker-compose`. Instructions are in README file.

**Comment by albinowax** [comment]
Thanks for the report. I've just fixed a bug which may resolve this as a side effect, hopefully.

**Comment by samincube** [comment]
Hi @albinowax,

Unfortunately, on version 1.23 the issue is still here. Seems like now miner reports only the first parameter detected and then drops the scan (without error messages).

**Comment by albinowax** [comment]
@samincube I've pushed an update that fixes the 'stops after one param' issue and makes sure any exceptions are actually displayed.

**Comment by samincube** [comment]
Hi @albinowax,

Tested out, it's fixed now, thank you!

**Comment by albinowax** [comment]
Excellent, thanks for the info!
